---
- name: 'Include OS specific variables'
  include_vars: 'ubuntu.yml'

# Ubuntu 10.04 or 12.04:
- name: 'Install required packages for Ubuntu 10.04 or 12.04'
  apt:
    name: "python-software-properties"
    state: present
  when: "{{ (ansible_distribution_version|int < 14) }}"

# Ubuntu 14.04:
- name: 'Install required packages for Ubuntu 14.04+'
  apt:
    name: "software-properties-common"
    state: present
  when: "{{ (ansible_distribution_version|int >= 14) }}"

- name: 'Add x2go repository'
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: x2go_apt_repositories

- name: 'Install x2go packages'
  apt:
    name: '{{ item }}'
    state: present
    install_recommends: yes
  with_items: x2go_apt_packages
